"""
map/adjacency_rules.txt 写入器.

参考: 参考/Map modding.txt 行 504-520.
- 必须 UTF-8 无 BOM (行 505)
- 多个 adjacency_rule = { ... } 块, 每块独立
- LF 换行
"""

from __future__ import annotations

import os


def write_adjacency_rules_txt(output_dir: str, rule_mgr=None) -> None:
    """生成 map/adjacency_rules.txt.

    rule_mgr: AdjacencyRuleManager 实例. None 或空时写空文件 (HOI4 接受空).
    """
    d = os.path.join(output_dir, "map")
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "adjacency_rules.txt")

    parts: list[str] = []
    parts.append("# Auto-generated by HOI4 MOD Maker")
    parts.append("# Adjacency rules — passage conditions for straits/canals.")
    parts.append("")

    if rule_mgr is not None:
        for rule in rule_mgr.get_all():
            parts.append(rule.to_block())
            parts.append("")

    content = "\n".join(parts) + "\n"
    with open(path, "wb") as f:
        f.write(content.encode("utf-8"))
